version: "3.7"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - network
    environment:
      POSTGRES_USER: "starter_kit"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DB: test
    volumes:
      - postgresdata:/var/lib/postgresql/data/


networks:
  network:
    driver: bridge

volumes:
  postgresdata:
