"""Added required tables

Revision ID: 00bc959d6665
Revises: b73bc823541d
Create Date: 2022-04-12 23:56:00.768442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00bc959d6665'
down_revision = 'b73bc823541d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
