"""Added required tables

Revision ID: 51d1451f08df
Revises: 00bc959d6665
Create Date: 2022-04-12 23:57:57.402893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d1451f08df'
down_revision = '00bc959d6665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
