"""Added required tables

Revision ID: 59b57bc3372e
Revises: e7efaf38ed73
Create Date: 2022-04-13 00:00:47.612553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b57bc3372e'
down_revision = 'e7efaf38ed73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
