"""Added required tables

Revision ID: 8c11cf489be2
Revises: f48700ad7144
Create Date: 2022-04-12 23:01:32.889443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c11cf489be2'
down_revision = 'f48700ad7144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
