"""Added required tables

Revision ID: e7efaf38ed73
Revises: 51d1451f08df
Create Date: 2022-04-12 23:58:15.232443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7efaf38ed73'
down_revision = '51d1451f08df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
